### ISSUE TITLE
couldn't find file 'bootstrap-tagmanager'

### ISSUE THREAD

**Issue by mhenrixon** [tmaier/tagmanager-rails#3]
``` ruby
# Gemfile
gem "tagmanager-rails"
```

``` js
// application.js
//= require bootstrap-tagmanager
```

> (in /Users/mhenrixon/Work/rushplay/casino-saga-backoffice/app/assets/javascripts/application.js:8)

``` scss
// application.css.scss
@import "bootstrap-tagmanager";
```

> File to import not found or unreadable: bootstrap-tagmanager.
> Load paths:
>   /Users/mhenrixon/Work/rushplay/casino-saga-backoffice/app/assets/javascripts
>   /Users/mhenrixon/Work/rushplay/casino-saga-backoffice/app/assets/stylesheets
>   /Users/mhenrixon/Work/rushplay/casino-saga-backoffice/vendor/assets/javascripts
>   /Users/mhenrixon/Work/rushplay/casino-saga-backoffice/vendor/assets/stylesheets
>   /Users/mhenrixon/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/turbolinks-1.3.0/lib/assets/javascripts
>   /Users/mhenrixon/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/tagmanager-rails-3.0.0/vendor/assets/javascripts
>   /Users/mhenrixon/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/tagmanager-rails-3.0.0/vendor/assets/stylesheets
>   /Users/mhenrixon/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/font-awesome-sass-rails-3.0.2.2/app/assets/fonts
>   /Users/mhenrixon/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/font-awesome-sass-rails-3.0.2.2/app/assets/stylesheets
>   /Users/mhenrixon/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bootstrap-sass-rails-3.0.0.3/app/assets/fonts
>   /Users/mhenrixon/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bootstrap-sass-rails-3.0.0.3/app/assets/javascripts
>   /Users/mhenrixon/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/bootstrap-sass-rails-3.0.0.3/app/assets/stylesheets
>   /Users/mhenrixon/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jquery-ui-rails-4.0.5/app/assets/images
>   /Users/mhenrixon/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jquery-ui-rails-4.0.5/app/assets/javascripts
>   /Users/mhenrixon/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jquery-ui-rails-4.0.5/app/assets/stylesheets
>   /Users/mhenrixon/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/jquery-rails-3.0.4/vendor/assets/javascripts
>   /Users/mhenrixon/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/coffee-rails-4.0.0/lib/assets/javascripts
>   (in /Users/mhenrixon/Work/rushplay/casino-saga-backoffice/app/assets/stylesheets/application.css.scss:3)
> /Users/mhenrixon/Work/rushplay/casino-saga-backoffice/app/assets/stylesheets/application.css.scss:3
> Tasks: TOP => assets:precompile
> (See full trace by running task with --trace)

**Comment by tmaier** [comment]
Thank you for reporting. I will check it out

**Comment by mhenrixon** [comment]
You renamed it to `tagmanager` that's why. The Readme wasn't updated however :)

**Comment by tmaier** [comment]
So this is a documentation issue. The file was renamed from `bootstrap-tagmanager` to `tagmanager` with the latest update

**Comment by tmaier** [comment]
You're right just realised it as well :)

**Comment by mhenrixon** [comment]
I would recommend also adding a post install message like we did with `wash_out`

``` ruby
  gem.post_install_message = <<-EOS
    Please replace `include WashOut::SOAP` with `soap_service`
    in your controllers if you are upgrading from a version before 0.8.5.
  EOS
```

**Comment by tmaier** [comment]
I released an update with this documentation fix. It's version 3.0.0.1

**Comment by tmaier** [comment]
By the way, it is better to mention the scss file explicitly

```
@import 'tagmanager.css.scss;
```

Else it will use the normal css file and not the scss version
