### ISSUE TITLE
Problem Getting Working (SASS complication?)

### ISSUE THREAD

**Issue by seanahrens** [tmaier/tagmanager-rails#6]
I'm using sass.

When I add the line
@import 'tagmanager.css.scss' (no ; as shown in the docs)
to application.css.sass,

I get the following error when I hit the server from the browser:

Undefined variable: "$gray".
  (in .../app/assets/stylesheets/application.css.sass:11)

I've also tried adding and including the .css and .js files manually -- in that case, I don't get this error, but the tag field doesn't function either.

Sorry for this abstract issue, but any thoughts of what might be causing that strange error? Also, since I'm using sass, I don't have the option that I can see of including the tagmanager css via the /\* require 'tagmanager' */ call as shown in in the docs. My application.css.scss file is all @imports.

**Comment by tmaier** [comment]
The semicolon is necessary in SCSS.

The variable $gray is defined in bootstrap.
(see https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss#L17)

Your problems sound like you add tagmanager-rails without adding bootstrap or you're loading bootstrap after loading tagmanager in your js and css files.

**Comment by mhenrixon** [comment]
I get this:

``` ruby
ActionView::Template::Error (Undefined variable: "$grayDark".
  (in /Users/mhenrixon/code/rushplay/casino-saga/admin/app/assets/stylesheets/application.css.scss:33)):
    2: html lang="en"
    3:   head
    4:     meta name="viewport" content="width=device-width, initial-scale=1.0"
    5:     = stylesheet_link_tag 'application'
    6:     = csrf_meta_tag
    7:     = javascript_tag "var autocomplete_items=#{@autocomplete_items.to_json};"
  app/assets/stylesheets/application.css.scss:9
  app/views/layouts/admin.html.slim:5:in `_app_views_layouts_admin_html_slim__1805223595776911642_70156961750900'
```

I have importet it after bootstrap as you can see in the below application.css,scss

``` scss
// application.css.scss
@import "bootstrap_overrides";
@import "bootstrap-sprockets";
@import "bootstrap";
@import "bootstrap/variables";
@import "bootstrap/mixins";
@import "font-awesome";
@import "bootstrap-datepicker";
@import "typeahead";
@import "tagmanager.css.scss"; # line 9
@import "header.scss";
```

**Comment by tmaier** [comment]
`$grayDark` is used in [line 33](https://github.com/tmaier/tagmanager-rails/blob/master/vendor/assets/stylesheets/tagmanager.css.scss#L33).

Version 3.0.1 has been released on December, 12th 2013. 
On December, 13th 2013 they pushed a commit to tagmanager fixing this issue: https://github.com/max-favilli/tagmanager/commit/f0df9c22aa779e2dc59c423d84c2ba38821ba724
For me, this would have been a very good reason to release Version 3.0.2...

You have two options in my opinion:
- define `$grayDark` by yourself. (Maybe set it to the same value as `$gray-dark`)
- Ask at https://github.com/max-favilli/tagmanager to use bootstrap default variables
- Ask at https://github.com/max-favilli/tagmanager to release a new version, so that we can update the gem here.

**Comment by tmaier** [comment]
I'm closing this, as the issues at hand are not related to the gem itself.
- Original issue was about order of the files imported.
- Second issue was about a problem of https://github.com/max-favilli/tagmanager itself and should be raised there.

**Comment by mhenrixon** [comment]
That is not the only issue I get problems with other removed bootstrap variables if I do so using tagsinput instead. Seems to be working fine so far though not as intuitive.

**Comment by tmaier** [comment]
> That is not the only issue I get problems with other removed bootstrap variables if I do so using tagsinput instead. Seems to be working fine so far though not as intuitive.

I don't understand this sentence, sorry.
